import { NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";

export async function GET(request: NextRequest) {
  const token = request.nextUrl.searchParams.get("token");

  if (!token) {
    return NextResponse.redirect(new URL("/unsubscribed?error=missing_token", request.url));
  }

  // Uses the service role key so this works without a user session.
  // The unsubscribe token acts as a single-use bearer credential —
  // it was generated by the server and emailed to the subscriber.
  const supabase = createAdminClient();

  const { error } = await supabase
    .from("newsletter_subscribers")
    .update({ is_active: false })
    .eq("unsubscribe_token", token);

  if (error) {
    return NextResponse.redirect(new URL("/unsubscribed?error=server_error", request.url));
  }

  return NextResponse.redirect(new URL("/unsubscribed", request.url));
}
